language: node_js
node_js:
- '0.12'
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start || true
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
